"""Autogenerated from Ziggurat's `wire.rs`. Do not edit."""

from __future__ import annotations

from typing import Self, cast

import zigpy.types as t


class DeliveryMode(t.enum2):
    UNICAST = 0
    BROADCAST = 2
    MULTICAST = 3


PROTOCOL_VERSION = 2


class RequestCommand(t.enum8):
    RESET = 0x00
    GET_FIRMWARE_INFO = 0x01
    GET_HW_ADDRESS = 0x02
    SHUTDOWN = 0x03
    CONFIGURE = 0x10
    LOAD_KEY_TABLE = 0x11
    LOAD_CHILDREN = 0x12
    LOAD_ADDRESS_CACHE = 0x13
    LOAD_ROUTE_TABLE = 0x14
    LOAD_SOURCE_ROUTES = 0x15
    START_NETWORK = 0x16
    GET_NETWORK_INFO = 0x20
    SCAN_KEY_TABLE = 0x21
    SCAN_CHILDREN = 0x22
    SCAN_ADDRESS_CACHE = 0x23
    SCAN_ROUTE_TABLE = 0x24
    SEND_UNICAST = 0x30
    SEND_BROADCAST = 0x31
    SEND_GROUPCAST = 0x32
    CANCEL_REQUEST = 0x33
    PERMIT_JOINS = 0x34
    SET_CHANNEL = 0x35
    SET_NWK_UPDATE_ID = 0x36
    SET_PROVISIONAL_KEY = 0x37
    SET_TUNABLE = 0x38
    ENERGY_SCAN = 0x40
    NETWORK_SCAN = 0x41
    PACKET_CAPTURE = 0x42
    PACKET_CAPTURE_CHANNEL = 0x43


class NotificationCommand(t.enum8):
    HELLO = 0x00
    LAST_RESET = 0x01
    RECEIVED_APS = 0x10
    SEND_CONFIRM = 0x11
    APS_ACK_CONFIRM = 0x12
    BROADCAST_CONFIRM = 0x13
    DEVICE_JOINED = 0x20
    DEVICE_LEFT = 0x21
    FRAME_COUNTER = 0x30
    APS_FRAME_COUNTER = 0x31
    LINK_KEY = 0x32
    APS_DECRYPT_FAILURE = 0x33
    ROUTE_RECORD = 0x34


class FrameType(t.enum2):
    REQUEST = 0
    RESPONSE = 1
    EVENT = 2
    NOTIFICATION = 3


class Status(t.enum8):
    OK = 0x00
    MALFORMED_PAYLOAD = 0x01
    UNKNOWN_COMMAND = 0x02
    INVALID_REQUEST = 0x03
    NOT_CONFIGURED = 0x10
    NOT_STARTED = 0x11
    ALREADY_STARTED = 0x12
    RATE_LIMITED = 0x20
    BUDGET_EXHAUSTED = 0x21
    PAYLOAD_TOO_LONG = 0x22
    SECURITY_UNAVAILABLE = 0x23
    NO_ROUTE = 0x24
    RADIO_ERROR = 0x30
    NETWORK_START_FAILED = 0x31
    SCAN_FAILED = 0x32
    RESPONSE_TOO_LARGE = 0x40


class NodeRole(t.enum8):
    COORDINATOR = 0
    ROUTER = 1


class TclkFlavorId(t.enum8):
    Z_STACK = 0
    EZSP = 1


class ChildDeviceType(t.enum2):
    UNKNOWN = 0
    ROUTER = 1
    END_DEVICE = 2


class KeyId(t.enum8):
    DATA = 0
    NETWORK = 1
    KEY_TRANSPORT = 2
    KEY_LOAD = 3


class LeaveReason(t.enum8):
    ANNOUNCED = 0
    ROUTER_REPORTED = 1
    KEEPALIVE_TIMEOUT = 2


# The 3-byte header leading every frame in both directions: the command byte, then
# a little-endian u16 equal to `request_id << 2 | frame_type`.
class Header(t.Struct):
    command: t.uint8_t
    frame_type: FrameType
    request_id: t.uint16_t

    def serialize(self) -> bytes:
        word = t.uint16_t((self.request_id << 2) | self.frame_type)
        return self.command.serialize() + word.serialize()

    @classmethod
    def deserialize(cls, data: bytes) -> tuple[Self, bytes]:
        command, data = t.uint8_t.deserialize(data)
        word, data = t.uint16_t.deserialize(data)
        return (
            cls(
                command=command,
                frame_type=FrameType(word & 0b11),
                request_id=t.uint16_t(word >> 2),
            ),
            data,
        )


class ResetPayload(t.Struct):
    hard: t.Bool


class FirmwareInfoPayload(t.Struct):
    protocol_version: t.uint8_t
    version: t.LongCharacterString


class HwAddressPayload(t.Struct):
    ieee: t.EUI64


class NetworkState(t.Struct):
    channel: t.uint8_t
    nwk_update_id: t.uint8_t
    pan_id: t.PanId
    extended_pan_id: t.ExtendedPanId
    nwk_address: t.NWK
    ieee_address: t.EUI64
    network_key: t.KeyData
    network_key_seq: t.uint8_t
    network_key_tx_counter: t.uint32_t
    tc_link_key: t.KeyData
    has_tclk_seed: t.Bool
    tclk_seed: t.KeyData
    tclk_flavor: TclkFlavorId
    tx_power: t.int8s
    aps_frame_counter: t.uint32_t


class ConfigurePayload(t.Struct):
    role: NodeRole
    source_routing: t.Bool
    state: NetworkState


class KeyEntry(t.Struct):
    key: t.KeyData
    tx_counter: t.uint32_t
    rx_counter: t.uint32_t
    seq: t.uint8_t
    partner_ieee: t.EUI64


class LoadKeyTablePayload(t.Struct):
    entries: t.LVList[KeyEntry, t.uint16_t]


class ChildEntry(t.Struct):
    ieee: t.EUI64
    nwk: t.NWK
    rx_on_when_idle: t.uint1_t
    device_type: ChildDeviceType
    reserved: t.uint5_t


class LoadChildrenPayload(t.Struct):
    entries: t.LVList[ChildEntry, t.uint16_t]


class AddressEntry(t.Struct):
    ieee: t.EUI64
    nwk: t.NWK


class LoadAddressCachePayload(t.Struct):
    entries: t.LVList[AddressEntry, t.uint16_t]


class RouteEntry(t.Struct):
    destination: t.NWK
    next_hop: t.NWK
    path_cost: t.uint8_t


class LoadRouteTablePayload(t.Struct):
    entries: t.LVList[RouteEntry, t.uint16_t]


class SourceRouteEntry(t.Struct):
    destination: t.NWK
    relays: t.LVList[t.NWK, t.uint8_t]


class LoadSourceRoutesPayload(t.Struct):
    entries: t.LVList[SourceRouteEntry, t.uint16_t]


class NetworkInfoPayload(t.Struct):
    state: NetworkState
    key_count: t.uint16_t
    started: t.Bool


class ScanCountPayload(t.Struct):
    count: t.uint16_t


class RouteControl(t.enum8):
    STACK_DECIDES = 0
    HINT_NEXT_HOP = 1
    FORCE_NEXT_HOP = 2
    HINT_SOURCE_ROUTE = 3
    FORCE_SOURCE_ROUTE = 4


class SourceRouteRelays(t.Struct):
    relays: t.LVList[t.NWK, t.uint8_t]


class SendUnicastPayload(t.Struct):
    has_eui64: t.uint1_t
    aps_ack: t.uint1_t
    aps_encryption: t.uint1_t
    sleepy_destination: t.uint1_t
    reserved: t.uint4_t
    destination: t.NWK
    destination_eui64: t.EUI64
    profile_id: t.uint16_t
    cluster_id: t.uint16_t
    src_ep: t.uint8_t
    dst_ep: t.uint8_t
    aps_seq: t.uint8_t
    radius: t.uint8_t
    priority: t.int8s
    route: RouteControl
    next_hop: t.NWK = t.StructField(  # type: ignore[assignment]
        requires=lambda s: cast(SendUnicastPayload, s).route
        in (RouteControl.HINT_NEXT_HOP, RouteControl.FORCE_NEXT_HOP)
    )
    relays: SourceRouteRelays = t.StructField(  # type: ignore[assignment]
        requires=lambda s: cast(SendUnicastPayload, s).route
        in (RouteControl.HINT_SOURCE_ROUTE, RouteControl.FORCE_SOURCE_ROUTE)
    )
    asdu: t.LongOctetString


class SendBroadcastPayload(t.Struct):
    reserved: t.uint8_t
    destination: t.NWK
    profile_id: t.uint16_t
    cluster_id: t.uint16_t
    src_ep: t.uint8_t
    dst_ep: t.uint8_t
    aps_seq: t.uint8_t
    radius: t.uint8_t
    priority: t.int8s
    asdu: t.LongOctetString


class SendGroupcastPayload(t.Struct):
    reserved: t.uint8_t
    group_id: t.uint16_t
    profile_id: t.uint16_t
    cluster_id: t.uint16_t
    src_ep: t.uint8_t
    aps_seq: t.uint8_t
    radius: t.uint8_t
    priority: t.int8s
    asdu: t.LongOctetString


class CancelRequestPayload(t.Struct):
    request_id: t.uint16_t


class CancelResultPayload(t.Struct):
    cancelled: t.Bool


class PermitJoinsPayload(t.Struct):
    duration: t.uint16_t
    accept_direct_joins: t.Bool


class ChannelPayload(t.Struct):
    channel: t.uint8_t


class NwkUpdateIdPayload(t.Struct):
    nwk_update_id: t.uint8_t


class ProvisionalKeyPayload(t.Struct):
    ieee: t.EUI64
    key: t.KeyData


class SetTunablePayload(t.Struct):
    name: t.LVBytes
    value: t.uint64_t


class ScanRequestPayload(t.Struct):
    channels: t.LVList[t.uint8_t, t.uint16_t]
    duration_per_channel_ms: t.uint16_t


class EnergyResultPayload(t.Struct):
    channel: t.uint8_t
    rssi: t.int8s


class BeaconPayload(t.Struct):
    channel: t.uint8_t
    source: t.NWK
    pan_id: t.PanId
    extended_pan_id: t.ExtendedPanId
    permit_joining: t.uint1_t
    router_capacity: t.uint1_t
    end_device_capacity: t.uint1_t
    reserved: t.uint5_t
    stack_profile: t.uint8_t
    protocol_version: t.uint8_t
    device_depth: t.uint8_t
    update_id: t.uint8_t
    lqi: t.uint8_t
    rssi: t.int8s


class CapturedPacketPayload(t.Struct):
    channel: t.uint8_t
    rssi: t.int8s
    lqi: t.uint8_t
    psdu: t.LongOctetString


class RateLimitedPayload(t.Struct):
    status: Status
    retry_in_ms: t.uint32_t


class HelloPayload(t.Struct):
    protocol_version: t.uint8_t
    configured: t.Bool


class LastResetPayload(t.Struct):
    message: t.LongCharacterString


class ReceivedApsPayload(t.Struct):
    source: t.NWK
    destination: t.NWK
    has_group: t.Bool
    group: t.uint16_t
    profile_id: t.uint16_t
    cluster_id: t.uint16_t
    src_ep: t.uint8_t
    dst_ep: t.uint8_t
    lqi: t.uint8_t
    rssi: t.int8s
    data: t.LongOctetString


class SendStatus(t.enum8):
    SUCCESS = 0
    ROUTE_DISCOVERY_TIMEOUT = 1
    ROUTE_DISCOVERY_NO_ENTRY = 2
    ROUTE_INACTIVE_AFTER_DISCOVERY = 3
    NWK_NO_ACK = 4
    CCA_FAILURE = 5
    TRANSMIT_FAILED = 6
    APS_ACK_TIMEOUT = 7
    BROADCAST_QUORUM_NOT_REACHED = 8
    INDIRECT_EXPIRED = 9
    FRAME_BUDGET_EXHAUSTED = 10
    CANCELLED = 11
    RADIO_ERROR = 12


class SendConfirmPayload(t.Struct):
    status: SendStatus


class ApsAckConfirmPayload(t.Struct):
    status: SendStatus


class BroadcastConfirmPayload(t.Struct):
    status: SendStatus


class DeviceJoinedPayload(t.Struct):
    nwk: t.NWK
    ieee: t.EUI64
    parent: t.NWK
    rx_on_when_idle: t.uint1_t
    device_type: ChildDeviceType
    reserved: t.uint5_t


class DeviceLeftPayload(t.Struct):
    nwk: t.NWK
    has_ieee: t.uint1_t
    rejoin: t.uint1_t
    has_router_ieee: t.uint1_t
    reserved: t.uint5_t
    ieee: t.EUI64
    reason: LeaveReason
    router: t.NWK
    router_ieee: t.EUI64


class FrameCounterPayload(t.Struct):
    frame_counter: t.uint32_t


class LinkKeyPayload(t.Struct):
    ieee: t.EUI64
    key: t.KeyData


class RouteRecordPayload(t.Struct):
    destination: t.NWK
    relays: t.LVList[t.NWK, t.uint8_t]


class ApsFrameCounterPayload(t.Struct):
    frame_counter: t.uint32_t


class ApsDecryptFailPayload(t.Struct):
    source: t.NWK
    source_ieee: t.EUI64
    frame_counter: t.uint32_t
    key_id: KeyId
